name: Nightly builds

on:
  schedule:
    - cron: '*/15 * * * *'

jobs:
 
  test_cron_a:
    name: Test scheduled build A
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - run: |
          mkdir foo
          date > foo/date.txt
      - uses: actions/upload-artifact@master
        env:
          DATE: test
        with:
          name: foo-${{ env.DATE }}
          path: foo

  test_cron_b:
    name: Test scheduled build B
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - run: |
          mkdir foo
          date > foo/date.txt
      - uses: actions/upload-artifact@master
        env:
          DATE: $(date +%H%M)
        with:
          name: foo-${{ env.DATE }}
          path: foo
