name: Foobar builds

on: [push, pull_request]

#  schedule:
#    - cron: '*/15 * * * *'

jobs:

  test:
    name: Test ${{ matrix.conf.name }} matrix 
    runs-on: ubuntu-18.04
    # prevent duplicate jobs when maintainer is pushing to PR:
    #if: !( ${{ env.GITHUB_EVENT_NAME }} == 'push' &&
    #       ${{ env.GITHUB_REF }} == 'po/*' )
    strategy:
      matrix:
        conf:
          - name: Foo
            value: foo
          - name: Bar
            value: bar
    steps:
      - run: echo ${{ env.GITHUB_EVENT_NAME }} ${{ env.GITHUB_REF }} ${{ github.ref }}

